---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: asd-ns
  name: asd-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c940e18da6cf1c8f

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asd-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 20Gi